export const PostsConstants = {
  ADD_POST: "ADD_POST",
  GET_POST: "GET_POST",
  GET_POSTS: "GET_POSTS",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",
  POST_ERRORS: "POST_ERRORS",
  CLEAR_POST_ERRORS: "CLEAR_POST_ERRORS",
  SET_POSTS_LOADING: "SET_POSTS_LOADING",
  CLEAR_POST_SUCCESS: "CLEAR_POST_SUCCESS",
};

export const AuthConstants = {
  LOGIN_USER: "LOGIN_USER",
  REGISTER_USER: "REGISTER_USER",
  GET_USER_BY_TOKEN: "GET_USER_BY_TOKEN",
  AUTH_ERROR: "AUTH_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  CLEAR_AUTH_ERRORS: "CLEAR_AUTH_ERRORS",
  UPDATE_USER_THUMBNAIL: "UPDATE_USER_THUMBNAIL",
  UPDATE_USER_THUMBNAIL_ERROR: "UPDATE_USER_THUMBNAIL_ERROR",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  SET_AUTH_LOADING: "SET_AUTH_LOADING",
};

export const CommentsConstants = {
  ADD_COMMENT: "ADD_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  GET_COMMENT: "GET_COMMENT",
  GET_COMMENTS: "GET_COMMENTS",
  COMMENT_ERRORS: "COMMENT_ERRORS",
  CLEAR_COMMENT_ERRORS: "CLEAR_COMMENT_ERRORS",
};

export const ServerErrorConstants = {
  SET_SERVER_ERROR: "SET_SERVER_ERROR",
  CLEAR_SERVER_ERROR: "CLEAR_SERVER_ERROR",
};

export const PicturesConstants = {
  SET_PICTURES_PATH: "SET_PICTURES_PATH",
};
